TradeOwl/src/TradeOwl/TradeBundle/Entity/PostPicture.php
<?php
/**
 * Created by PhpStorm.
 * User: john
 * Date: 8/22/14
 * Time: 3:39 PM
 */

namespace TradeOwl\TradeBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use Doctrine\Common\PropertyChangedListener;
use Doctrine\Common\NotifyPropertyChanged;
use Symfony\Component\HttpFoundation\File\UploadedFile;
use Symfony\Component\Validator\Constraints as Assert;


/**
 * @ORM\Entity
 * @ORM\Table(name="tblPostPicture")
 * @ORM\HasLifecycleCallbacks
 */
class PostPicture
{
    private $temp;//TODO: fix this janky nonsense

    /**
     * @ORM\Id
     * @ORM\Column(type="integer", name="postPic_id")
     * @ORM\GeneratedValue(strategy="IDENTITY")
     */
    protected $id;

    /**
     * @ORM\Column(name="postPic_filePath",type="string", length=255, nullable=false)
     */
    protected $path; //TODO:add logic for subdirectories

    /**
     * @ORM\ManyToOne(targetEntity="PostItem",fetch="EXTRA_LAZY", inversedBy="pics")
     * @ORM\JoinColumn(name="postItem_id", referencedColumnName="postItem_id", nullable=true)
     */
    protected $postItem;

    /**
     * @Assert\Image(maxSize="6000000")
     */
    private $file; //TODO:add more validation assertions

    public function copy(\TradeOwl\TradeBundle\Entity\PostPicture $pic){
        $this->setFile($pic->getFile());
        $this->setPath($pic->getPath());
    }
    /**
     * @param UploadedFile $file
     */
    public function setFile(UploadedFile $file = null)
    {
        $this->file = $file;
        if (isset($this->path)) {
            $this->temp = $this->path;
            $this->path = null;
        } else {
            $this->path = 'initial';
        }
    }

    /**
     * @return UploadedFile
     */
    public function getFile()
    {
        return $this->file;
    }

    /**
     * @ORM\PrePersist()
     * @ORM\PreUpdate()
     */
    public function preUpload()
    {
        if ($this->getId() == 12){
            throw new \Exception("Attempted to change default user pic!");
        }
        if (null !== $this->getFile()) {
            $filename = sha1(uniqid(mt_rand(), true));
            $this->path = $filename . '.' . $this->getFile()->guessExtension();
        }
    }

    public function getAbsolutePath()
    {
        return null === $this->path
            ? null
            : $this->getUploadRootDir() . '/' . $this->path;
    }


    public function getWebPath()
    {
        return null === $this->path
            ? null
            : $this->getUploadDir() . '/' . $this->path;
    }

    public function getThumbWebPath(){
        return null === $this->path
            ? null
            : $this->getUploadDir() . '/' . $this->getThumbPath();
    }

    public function getSourceWebPath(){
        return '/'.$this->getWebPath();
    }

    public function getThumbPath(){
        return 'thm'.$this->getPath();
    }

    public function getThumbSourceWebPath(){
        return '/'.$this->getThumbWebPath();
    }

    protected function getUploadRootDir()
    {
        return __DIR__ . '/../../../../web/' . $this->getUploadDir();
    }

    protected function getUploadDir()
    {
        return 'uploads/media';
    }

    /**
     * @ORM\PostPersist()
     * @ORM\PostUpdate()
     */
    public function upload()
    {
        if (null === $this->getFile()) {
            return;
        }
        $ext = $this->getFile()->guessExtension();
        $fullpath = $this->getUploadRootDir() . '/' . $this->path;

        $this->getFile()->move($this->getUploadRootDir(), $this->path);

        $w = 300;
        $h = 300;
        $thumb = ImageCreateTrueColor($w, $h);
        ImageColorTransparent($thumb, ImageColorAllocateAlpha($thumb, 0, 0, 0, 127));
        ImageAlphaBlending($thumb, false);
        ImageSaveAlpha($thumb, true);
        $image = "";
        if ($ext === "png") {
            $image = imagecreatefrompng($fullpath);
        } elseif ($ext === "gif") {
            $image = imagecreatefromgif($fullpath);
        } elseif ($ext === "jpeg" || $ext === "jpg") {
            $image = imagecreatefromjpeg($fullpath);
        } else {
            throw new Exception($ext); //TODO:handle this more gracefully
        }
        $x = ImageSX($image);
        $y = ImageSY($image);
        $scale = min($x / $w, $y / $h);
        ImageCopyResampled($thumb, $image, 0, 0, ($x - ($w * $scale)) / 2, ($y - ($h * $scale)) / 2, $w, $h, $w * $scale, $h * $scale);
        ImagePNG($thumb, $this->getUploadRootDir() . '/' . $this->getThumbPath());

        if (isset($this->temp)) {
            unlink($this->getUploadRootDir() . '/' . $this->temp);
            $this->temp = null;
        }
        $this->file = null;
    }

    /**
     * @ORM\PostRemove()
     */
    public function removeUpload()
    {
        if ($file = $this->getAbsolutePath()) {
            unlink($file);
            unlink($this->getUploadRootDir() . '/' . $this->getThumbPath());
        }
    }

    /**
     * Get id
     *
     * @return integer
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set path
     *
     * @param string $path
     * @return PostPicture
     */
    public function setPath($path)
    {
        $this->path = $path;

        return $this;
    }

    /**
     * Get path
     *
     * @return string
     */
    public function getPath()
    {
        return $this->path;
    }

    /**
     * Set postItem
     *
     * @param \TradeOwl\TradeBundle\Entity\PostItem $postItem
     * @return PostPicture
     */
    public function setPostItem(\TradeOwl\TradeBundle\Entity\PostItem $postItem = null)
    {
        $this->postItem = $postItem;

        return $this;
    }

    /**
     * Get postItem
     *
     * @return \TradeOwl\TradeBundle\Entity\PostItem
     */
    public function getPostItem()
    {
        return $this->postItem;
    }

    /**
     * Get ImgDisplay
     *
     * @return string
     */

    public function getImgDisplay()
    {


        if ($this->id) {
            return $this->getUploadDir() . $this->getPostItem();
        } else {

            return "No pic";
        }
    }

    /**
     * Constructor
     */
    public function __construct()
    {
    }
}

TradeOwl/src/TradeOwl/TradeBundle/Controller/PostController.php
<?php
/**
 * Created by PhpStorm.
 * User: john
 * Date: 8/25/14
 * Time: 9:46 AM
 */

namespace TradeOwl\TradeBundle\Controller;

use Doctrine\Common\Collections\ArrayCollection;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Security\Acl\Exception\Exception;
use Symfony\Component\Security\Core\SecurityContextInterface;
use Symfony\Component\Validator\Constraints\Collection;
use TradeOwl\TradeBundle\Entity\GeoFilter;
use TradeOwl\TradeBundle\Entity\PostItem;
use TradeOwl\TradeBundle\Form\PostItemType;
use TradeOwl\TradeBundle\Form\GeoFilterType;
use TradeOwl\TradeBundle\Entity\PostPicture;

class PostController extends Controller
{
    public function display(Request $request, $message = "", $id = null, $action = 'trade_owl_trade_post_create')
    {
        $em = $this->getDoctrine()->getManager();
        $user = $this->container->get('security.context')->getToken()->getUser();
        $post = new PostItem();
        $post->setUser($user);
        if (is_null($user->getPicNrml())){
            $defPic = $em->getRepository('TradeOwlTradeBundle:PostPicture')->find(12);
            $newPic = new PostPicture();
            $newPic->copy($defPic);
            $user->setPicNrml($newPic);
        }

        //If an id is passed in then we're either modifying or viewing a post
        if ($id !== null) {
            $post = $em->getRepository('TradeOwlTradeBundle:PostItem')->find($id); //get the repository
            if (!$post) {
                throw $this->createNotFoundException('Post not found!'); //TODO:handle more gracefully
            }
            foreach ($post->getPics() as $pic) {
                $pic->setPostItem($post); //TODO: cleanup
            }
        }

        foreach ($user->getChainsStartedByMe() as $chain){
            $chains[] = $chain;
        }


        if ($request->getMethod() == 'POST') {
            $previousPics = new ArrayCollection();
            if ($action === 'trade_owl_trade_post_edit') {
                foreach ($post->getPics() as $pic) {
                    $previousPics->add($pic);
                }
            }
//            $post->setGeoFilter(new GeoFilter());
            $form = $this->createForm(new PostItemType($post->getUser()), $post);
//            throw new Exception($post->getGeoFilter()->getId());
            if ($post->getUser()->getId() !== $user->getId()) {
                throw new Exception("User not authorized to edit post!"); //TODO:handle more gracefully
            }
            $form->handleRequest($request);
            if ($form->isValid()) {
                foreach ($previousPics as $pic) {
                    if (!$post->getPics()->contains($pic)) {
                        $em->remove($pic);
                    }
                }
                foreach ($post->getPics() as $pic) {
                    $pic->setPostItem($post); //TODO:cleanup
                }
                $em->persist($post);
                $em->flush();
                return $this->redirect($this->generateUrl('trade_owl_trade_post_success'));
            }
        } else if ($request->getMethod() == 'GET') {

            $pics = $post->getPics();
            $post->resetPics();
            $form = $this->createForm(new PostItemType($post->getUser()), $post);
            $post->resetPics($pics);

            //begin geo
            $filter = new GeoFilter();
            $filter->setUser($user);
            $geoForm = $this->createForm(new GeoFilterType(), $filter);
            //end geo
            return $this->render('TradeOwlTradeBundle:Post:post_edit.html.twig', array('postMessage' => $message,
                'form' => $form->createView(), 'pics' => $post->getPics(), 'action' => $action, 'postId' => $id,
                'geoForm' => $geoForm->createView(), 'polygons' => $filter->getPolygons(),
                'geoAction' => 'trade_owl_trade_geo_save'));
        }
    }

    public function createAction(Request $request, $message = "")
    {
        return $this->display($request);
    }

    public function successAction(Request $request)
    {
        return $this->display($request, "Your item was posted successfully!");
    }

    public function editAction(Request $request, $id)
    {
        return $this->display($request, "", $id, 'trade_owl_trade_post_edit');
    }

    public function viewAction($id)
    {
        $this->get('twig')->addExtension(new \Twig_Extension_Debug);
        $em = $this->getDoctrine()->getManager(); //get the Entity Manager
        $post = $em->getRepository('TradeOwlTradeBundle:PostItem')->find($id); //get the repository

        if (!$post) {
            throw $this->createNotFoundException('No posts found ');
        }

        $comments = array();
        foreach ($post->getComments() as $comment){
            $i=0;
            for(;$i<count($comments);$i++){
                if ($comments[$i]->getCreateDttm() > $comment->getCreateDttm()){
                    break;
                }
            }
            if ($i < count($comments)){
                $tail = array_splice($comments, $i);
                $comments[] = $comment;
                foreach($tail as $val){
                    $comments[] = $val;
                }
            } else {
                $comments[] = $comment;
            }
        }
        $post->getComments()->clear();
        foreach($comments as $comment){
            $post->addComment($comment);
        }

        if(is_null($post->getUser()->getPicNrml())){
            $defPic = $em->getRepository('TradeOwlTradeBundle:PostPicture')->find(12);
            $newPic = new PostPicture();
            $newPic->copy($defPic);
            $post->getUser()->setPic(array($newPic));
        }

        return $this->render('TradeOwlTradeBundle:Post:post_view.html.twig', array(
            'post' => $post
        ));
    }


}

TradeOwl/src/TradeOwl/TradeBundle/Resources/views/Post/post_edit.html.twig
{% extends '::base.html.twig' %}
 {% block javascripts %}
     {{ parent() }}

     <!--begin geo-->
     <meta name="viewport" content="initial-scale=1.0, user-scalable=no">
     <script src="https://maps.googleapis.com/maps/api/js?v=3.exp&libraries=drawing&key=AIzaSyDqAFu6_aSRApv1XdAE2p4BTvhJqjgR8pU"></script>
     <script src="{{ asset('js/geo.js') }}"></script>
     <!--end geo-->
     <script>
         var lastPicNum = 0;
         var picNamePlaceHolder = "_pic_name_placeholder_";

         function showThumb(picNum, file) {
             var reader = new FileReader();
             reader.readAsDataURL(file);
             reader.onloadend = function () {
                 $("#post_pics_" + picNum).append('<div><img id="post_pics_' + picNum + '_thumb" src="' + this.result + '"/></div>');
             }
         }

         //TODO:superduper janky, maybe we just specify and maintain our own prototype
         function addFileLookup(picNum) {
             var newHtml = String(document.getElementById('post_pics').getAttribute('data-prototype').toString().trim())
                             .replace(new RegExp('_pic_name_placeholder_', 'g'), String(picNum)).trim()
                             .replace(new RegExp('<label .*label>'), '').trim()
                     ;
             $("#post_pics_list").append(newHtml);
             $("#post_pics_" + picNum + "_file").change(handlePicChange);
             $("#post_pics_" + picNum + "_remove").click(handlePicRemove);
             $("#post_pics_" + picNum + "_remove").prop("disabled", true);
             $("#post_pics_" + picNum + "_remove").prop("enabled", false);
             //$(":file").filestyle({size:"sm", input:false});
         }

         function handlePicChange(event) {
             var targPicNum = parseInt(String(event.target.id).substr("post_pics_".length, String(event.target.id).lastIndexOf("_file")));
             if (targPicNum == lastPicNum && event.target.value != null && String(event.target.value).trim().localeCompare("") != 0
                     && this.files.length < 5) {
                 lastPicNum++;
                 addFileLookup(lastPicNum);
                 var targPicRemove = "#post_pics_" + targPicNum + "_remove";
                 $(targPicRemove).prop("disabled", false);
                 $(targPicRemove).prop("enabled", true);
                 $(targPicRemove).prop('class', 'removePicButtonEnabled');
                 showThumb(targPicNum, event.target.files[0]);
             } else if (String(event.target.value).trim().localeCompare("") != 0) {
                 $("#post_pics_" + targPicNum + "_thumb").remove();
                 showThumb(targPicNum, event.target.files[0]);
             }
         }

         function handlePicRemove(event) {
             $("#" + event.target.id).parent().parent().remove();
         }

         $(document).ready(function () {
             lastPicNum = $('#post_pics_list > div').length;
             for (var picCount = 0; picCount < $('#post_pics_list > div').length; picCount++) {
                 $('#post_pics_' + picCount + '_file').change(handlePicChange);
                 $('#post_pics_' + picCount + '_remove').click(handlePicRemove);
                 $('#post_pics_' + picCount + '_remove').prop('enabled');
                 $('#post_pics_' + picCount + '_remove').prop('class', 'removePicButtonEnabled');
             }
             addFileLookup(lastPicNum);
         });
     </script>
     <!--begin geo-->
     <style>
         #map-canvas {
             position: relative;
             height: 400px;
             margin: 0px;
             padding: 0px
         }
     </style>
     <!--end geo-->
 {% endblock %}
{% block body %}
    {% if post_message is defined %}
        <div class="alert alert-dismissable alert-success">
            <button type="button" class="close" data-dismiss="alert">×</button>
            <strong>Oh Great!</strong>
            {{ postMessage }}
        </div>
    {% endif %}
    {% if form_errors is defined %}
        <div class="alert alert-danger" role="alert">
            {{ form_errors(form) }}
        </div>
    {% endif %}
    <form id="postForm" action="{{ path(action) }}/{{ postId }}" method="post" {{ form_enctype(form) }}>
        <div class="row">


            <div class="col-lg-8 col-xs-10">
                <div class="formTitle longInput">  {{ form_row(form.title) }} </div>
                <div class="formBody">  {{ form_row(form.body) }} </div>
            </div>

            <div class="col-lg-3 col-xs-10 panel panel-default">
                <div class="formPics">
                    {{ form_rest(form) }}
                    <button id="modalButton" data-toggle="modal" data-target="#myModal">
                        Create New GeoFilter
                    </button>
                    <hr>
                    Edit Pictures:
                    {{ form_row(form.pics) }}
                    <div id="post_pics_list">
                        {% for pic in pics %}
                            <div>
                                <div id="post_pics_{{ loop.index0 }}">
                                    <div>
                                        <input type="file" id="post_pics_{{ loop.index0 }}_file"
                                               name="post[pics][{{ loop.index0 }}][file]" value="">
                                    </div>
                                    <div>
                                        <button type="button" id="post_pics_{{ loop.index0 }}_remove" name="post[pics][{{ loop.index0 }}][remove]" class="removePicButtonEnabled">
                                            Remove
                                        </button>
                                    </div>
                                    <div>
                                        <img class="thumbnail" id="post_pics_{{ loop.index0 }}_thumb" src="{{ pic.thumbSourceWebPath }}"/>
                                    </div>
                                </div>
                            </div>
                        {% endfor %}
                    </div>
                </div>
            </div>
        </div>
        <input type="submit" value="Submit" name="submitButton" id="submitButton"/>
    </form>
    {% include 'TradeOwlTradeBundle:Geo:geo_edit.html.twig' %}
{% endblock %}